### ISSUE TITLE
Support PATCH

### ISSUE THREAD

**Issue by djeebus** [vroomy/vroomy#18]
For some reason, service.go's `initRoutes` doesn't support PATCH. Seems like a strange omission, let's add it. Or better yet, since the current implementation prevents us from building a WebDAV implementation (which uses methods like COPY, LOCK, MKCOL, etc), let's rework the internals so that we can just pass a `map` of methods around, removing the need for this switch statement completely.

**Comment by itsmontoya** [comment]
@djeebus dynamic methods are now supported. Sorry for not setting this as resolved immediately!
