### ISSUE TITLE
Vroomy parses the default config before parsing an alternate config

### ISSUE THREAD

**Issue by djeebus** [vroomy/vroomy#21]
This causes it to bail if it cannot parse the default config. For example:

If `config.toml` includes an `env.toml` file that does not exist, but we've called `vroomy -config altConfig.toml seed` (seed being a dynamic command) which is valid, it prints an error instead.

**Comment by dhalman** [comment]
@djeebus i think this is more specifically related to parsing dynamic commands from a non-default config

**Comment by itsmontoya** [comment]
This issue is related to commands. Commands have not been in vroomy for a few years, so I am going to close this.
